In [1]:
sim.dat <- read.csv("data/SegData.csv")

In [2]:
sim.dat

       age    gender income    house  store_exp online_exp store_trans
1      57     Female 120963.4  Yes    529.1344  303.5125    2
2      63     Female 122008.1  Yes    478.0058  109.5297    4
3      59     Male   114202.3  Yes    490.8107  279.2496    7
4      60     Male   113616.3  Yes    347.8090  141.6698   10
5      51     Male   124252.6  Yes    379.6259  112.2372    4
6      59     Male   107661.5  Yes    338.3154  195.6870    4
7      57     Male   120483.3  Yes    482.5445  284.5363    5
8      57     Male   110542.0  Yes    340.7368  135.2556   11
9      61     Female 132060.5  Yes    608.2310  142.5503    6
10     60     Male   105048.8  Yes    470.3190  163.4663   12
11     58     Male   107196.7  Yes    366.6393  170.1333    5
12     59     Male         NA  Yes    674.8829  310.2657    6
13     64     Male   119020.0  Yes    613.9490  160.8463    7
14     57     Female       NA  Yes    737.0497  224.5322    7
15     64     Male   114539.4  Yes    402.4901  241.8339    5
16     61     Female       NA  Yes    615.0562  238.0981    5
17     57     Female 133078.2  Yes    429.4224  262.6579    5
18     63     Male   115708.7  Yes    552.5769  187.5240    5
19     57     Female 113211.0  No     540.2776  254.5801    7
20     57     Female 129773.9  No     384.3378  311.0294    4
21     58     Male         NA  Yes    372.4081  296.8271   11
22     58     Male   124356.7  Yes    535.4838  205.5435    7
23     59     Female 123116.8  Yes    481.2511  157.2884    6
24     61     Female       NA  Yes    546.1564  161.2319    8
25     60     Female       NA  Yes    411.0873  123.7766   11
26     56     Male         NA  Yes    492.6820  128.0167    7
27     58     Male   127886.6  Yes    519.2970  142.6253    6
28     64     Male   115925.3  Yes    627.7060  240.9770    4
29     63     Female       NA  Yes    511.0623  203.4867    4
30     56     Female 112620.9  Yes    699.3193  223.4428    9
<U+22EE> <U+22EE> <U+22EE> <U+22EE>  <U+22EE> <U+22EE>  <U+22EE>   <U+22EE>
971    26     Female  84161.75 No     189.8271  1441.6129  3
972    23     Male    88608.68 Yes    214.1797  2846.3438  3
973    22     Female        NA Yes    202.4982  2319.0948  3
974    24     Female  84310.26 Yes    194.1801  1424.4339  3
975    26     Male    86864.20 No     189.6099  1471.7038  3
976    22     Male    81594.65 No     189.8746  1832.2623  3
977    26     Female  86015.77 No     201.1735  3210.1191  3
978    23     Male    86793.76 No     202.6480  2093.1900  1
979    26     Female  95341.78 No     198.9729  2036.4738  3
980    28     Female  88251.04 No     220.2917  2097.2648  2
981    27     Female  92442.39 Yes    202.8210  1800.5743  3
982    21     Female  88723.05 Yes    202.4166  1525.7441  3
983    27     Male   100161.94 Yes    209.4504   995.3551  3
984    26     Female  84919.18 Yes    186.3911  2216.2131  1
985    28     Female  88604.58 Yes    209.8301  2124.7940  1
986    27     Male    94157.43 No     213.9465  2618.8994  2
987    24     Female  92569.96 Yes    201.4508  2093.8541  3
988    22     Female        NA Yes    190.8787  1752.0292  3
989    26     Female  86990.85 No     207.1982  1528.8094  2
990    23     Male    96071.51 No     193.8734  1128.6300  6
991    25     Male    88151.69 Yes    201.8566  2675.7310  3
992    22     Male    80838.71 No     195.9793  2621.3046  1
993    27     Female  93987.33 No     202.7082  1684.6321  3
994    24     Female  94993.49 No     199.9065  2216.1617  4
995    21     Male    95579.26 No     192.5696  2489.2588  4
996    23     Female  88040.50 No     206.0094  1885.0874  2
997    25     Female  91033.57 No     198.7070  2437.6234  2
998    26     Female 100723.77 No     194.9919  2360.3634  2
999    23     Male    88926.06 No     190.6876  1724.0293  1
1000   26     Female  94769.39 No     199.6638  2482.6622  3
       online_trans Q1     Q2     Q3     Q4     Q5     Q6     Q7     Q8
1      2            4      2      1      2      1      4      1      4
2      2            4      1      1      2      1      4      1      4
3      2            5      2      1      2      1      4      1      4
4      2            5      2      1      3      1      4      1      4
5      4            4      1      1      3      1      4      1      4
6      5            4      2      1      2      1      4      1      4
7      3            4      1      1      2      1      4      1      4
8      5            5      2      1      3      1      4      1      4
9      1            4      1      1      2      1      4      1      4
10     1            4      2      1      3      1      4      1      4
11     4            4      1      1      3      1      4      1      4
12     2            4      1      1      3      1      4      1      4
13     4            5      1      1      3      1      4      1      4
14     3            4      2      1      3      1      4      1      4
15     5            4      2      1      2      1      4      1      4
16     1            5      2      1      2      1      4      1      4
17     3            5      2      1      2      1      4      1      4
18     2            5      2      1      3      1      4      1      4
19     2            4      2      1      3      1      4      1      4
20     2            5      2      1      2      1      4      1      5
21     2            5      1      1      3      1      4      1      4
22     3            4      2      1      2      1      4      1      4
23     1            5      2      1      2      1      4      1      4
24     3            5      1      1      2      1      4      1      4
25     3            4      1      1      3      1      4      1      4
26     1            5      1      1      3      1      4      1      4
27     2            4      1      1      3      1      4      1      4
28     4            5      1      1      2      1      4      1      4
29     3            5      1      1      2      1      4      1      4
30     2            5      2      1      2      1      4      1      4
<U+22EE> <U+22EE>     <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE>
971    22           2      1      1      1      4      1      5      3
972    19           2      1      1      2      4      1      5      3
973    27           3      1      1      1      4      1      4      3
974    27           3      1      1      1      4      1      4      3
975    23           2      1      1      1      4      1      4      2
976    21           3      1      1      1      4      1      4      2
977    17           2      1      1      2      4      1      5      2
978    25           2      1      1      2      4      1      5      2
979    21           3      1      1      2      4      1      5      2
980    18           3      1      1      1      4      1      5      3
981    22           3      1      1      1      4      1      4      3
982    17           3      1      1      1      4      1      4      2
983    30           3      1      1      1      4      1      5      3
984    16           3      1      1      2      4      1      5      3
985    25           2      1      1      2      4      1      4      3
986    15           2      1      1      2      4      1      4      3
987    17           2      1      1      1      4      1      4      3
988    22           2      1      1      2      4      1      5      2
989    18           3      1      1      2      5      1      4      3
990    21           3      1      1      2      4      1      4      3
991    23           2      1      1      1      4      1      5      2
992    24           3      1      1      1      4      1      4      2
993    15           2      1      1      1      4      1      4      3
994    19           2      1      1      2      4      1      4      2
995    20           3      1      1      2      4      1      4      3
996    19           3      1      1      2      4      1      4      2
997    29           3      1      1      1      4      1      5      3
998    24           3      1      1      2      4      1      5      2
999    23           2      1      1      2      4      1      5      3
1000   16           2      1      1      1      4      1      5      3
       Q9     Q10    segment
1      2      4      Price
2      1      4      Price
3      1      4      Price
4      2      4      Price
5      2      4      Price
6      1      4      Price
7      1      4      Price
8      2      4      Price
9      1      4      Price
10     1      4      Price
11     2      4      Price
12     1      4      Price
13     2      4      Price
14     1      4      Price
15     1      4      Price
16     1      4      Price
17     1      4      Price
18     2      4      Price
19     2      4      Price
20     2      4      Price
21     1      4      Price
22     2      4      Price
23     1      4      Price
24     2      4      Price
25     1      4      Price
26     2      4      Price
27     2      4      Price
28     2      4      Price
29     1      4      Price
30     2      4      Price
<U+22EE> <U+22EE> <U+22EE> <U+22EE>
971    4      1      Style
972    4      2      Style
973    4      2      Style
974    4      2      Style
975    4      1      Style
976    4      1      Style
977    4      2      Style
978    4      2      Style
979    4      1      Style
980    4      2      Style
981    4      1      Style
982    4      2      Style
983    4      2      Style
984    4      1      Style
985    4      1      Style
986    4      1      Style
987    4      2      Style
988    4      2      Style
989    4      1      Style
990    4      2      Style
991    4      2      Style
992    4      2      Style
993    4      1      Style
994    4      2      Style
995    4      2      Style
996    4      2      Style
997    4      1      Style
998    4      1      Style
999    4      2      Style
1000   4      2      Style

In [3]:
nrow(sim.dat)

[1] 1000

In [4]:
set.seed(12345)

In [5]:
ncust<-1000

In [6]:
seg_dat<-data.frame(id=as.factor(c(1:ncust)))

In [9]:
seg_dat

       id
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10     10
11     11
12     12
13     13
14     14
15     15
16     16
17     17
18     18
19     19
20     20
21     21
22     22
23     23
24     24
25     25
26     26
27     27
28     28
29     29
30     30
<U+22EE> <U+22EE>
971    971
972    972
973    973
974    974
975    975
976    976
977    977
978    978
979    979
980    980
981    981
982    982
983    983
984    984
985    985
986    986
987    987
988    988
989    989
990    990
991    991
992    992
993    993
994    994
995    995
996    996
997    997
998    998
999    999
1000   1000